### ISSUE TITLE
Using different languages

### ISSUE THREAD

**Issue by tur-ing** [watson-developer-cloud/movieapp-dialog#15]
I really love the Watson services and that they are available on Bluemix for everyone. Most of the services are working with language. So can I use the Dialog & NLC service with Spanish, German, Polish or any other language?

Best,

Marcel

**Comment by mitchmason** [comment]
Technically Dialog is language agnostic. If you are using non-english characters you will simply need to find the optimal way to put these in your dialog models, but the underlying service won't mind.

We have done development work on Spanish, Japanese, Portuguese, Czech, and English. This includes libraries of concepts known as parent accounts, as well as system entities. The documentation for these will be released in the near future. 

Natural Language Classifier has to be trained on the individual languages, and they currently support Protuguese, Spanish, Arabic, French, Italian, and English, which can be seen here:
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/nl-classifier/release_notes.shtml

More languages will become available as we do the required development work throughout the year.
