### ISSUE TITLE
Generate training data files

### ISSUE THREAD

**Issue by tur-ing** [watson-developer-cloud/movieapp-dialog#17]
Is there a way to generate the training data for the dialog and classifier service in an appropriate way? Because doing this manually seems to take weeks.

**Comment by germanattanasio** [comment]
Hi @tur-ing check this sample: https://github.com/watson-developer-cloud/conversational-agent-application-starter-kit it's the same idea but the app was written in Node.js, check the README and the links there.

Once you replace the credentials the app will automatically train the services for you

**Comment by tur-ing** [comment]
OK thank you @germanattanasio!
