### ISSUE TITLE
error while uploading dialog file

### ISSUE THREAD

**Issue by rhaenggi** [watson-developer-cloud/movieapp-dialog#19]
I'm trying to use your movieapp-dialog sample but failing while using the curl command, see my attached command.
curl -u "uid":"pw" -X POST --form "file=@roha-movieapp-dialog-file.xml" --form "name=roha-dialog-sample-service" "https://gateway.watsonplatform.net/dialog/api/v1/dialogs"

The error messages i get is:
```{"code":422, "error": "Valid name not specified. Expecting a short character string."}```
Any idea where this problem is related?

Even when I use the simple curl command
```curl -u "uid":"pw" "https://gateway.watsonplatform.net/dialog/api/v1"```
I get a different error:
```{"code": 500, "message": "Forwarding error"}```
Thanks for help
Regards
Roland

**Comment by germanattanasio** [comment]
`Forwarding error` is a common error and means that the service could be down.

**Comment by jsstylos** [comment]
This is a bug in the service that a GET on the top level `/v1` resource produces a 500 error, and is incorrectly using "message" instead of "error". The correct response would be a 404.

**Comment by germanattanasio** [comment]
@rhaenggi try to use another name for the dialog also. The name has to be unique.

**Comment by rhaenggi** [comment]
@germanattanasio Thanks for the tip, when I use the name of the dialog as "roha-dialog" it works and on the other topic when i add the /dialogs this works as fell.
Thanks a lot
