### ISSUE TITLE
Update reference material

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/movieapp-dialog#7]
In the bottom, under reference material, please update all documentation to new Dialog XML tutorials on bluemix.

**Comment by sgregglives** [comment]
I just pushed these changes. Let's make sure they're correct before we close out the issue.

**Comment by mitchmason** [comment]
looks good. can you close it or do I have to do that?
Regards,

Mitchell Mason
Product Manager - Watson Engagement Advisor - Dialog Services

Mobile: 408-981-3165
E-mail: mmason@us.ibm.com


650 Harry Road
San Jose, CA 95120
United States
