### ISSUE TITLE
Remove parent account from xml file

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/movieapp-dialog#8]
Please remove the parentconcepts account from the settings menu in all 3 xml files. 

This line overwrites the new language packs that are much more helpful.

**Comment by mitchmason** [comment]
In CA_Tran_Template its line 1500
In movieapp-dialog+classifier-file.xml its line 4922 (not parentconcepts, but will still cause problems)
In movieapp-dialog-file.xml its like 4685 (again, not parentconcepts, but still)

**Comment by germanattanasio** [comment]
Is this something we should do @mitchmason ?

**Comment by mitchmason** [comment]
Might be better to change it to 
en-us-legacy
as parentconcepts does not exist on bluemix so its not functional, and if its there it actually overwrites the actual language packs we want to use. en-us-legacy is the actual language pack so change parentconcepts to that.
