### ISSUE TITLE
Link to post describing how Dialog Services uses Natural Language Classifier's output

### ISSUE THREAD

**Issue by xverges** [watson-developer-cloud/movieapp-dialog#9]
This post could be added to the reference section: it allowed me to understand how Dialog uses the output from the Natural Language Classifier, a concept that was escaping me.

http://heidloff.net/article/cognitive-question-answer-systems-bluemix-watson

**Comment by germanattanasio** [comment]
done

**Comment by mitchmason** [comment]
I get a "server not found" when trying the link below. 

Regards,

Mitchell Mason
Product Manager - Watson Engagement Advisor - Dialog Services

Mobile: 408-981-3165
E-mail: mmason@us.ibm.com


650 Harry Road
San Jose, CA 95120
United States

**Comment by germanattanasio** [comment]
Mitch the link is
http://heidloff.net/article/cognitive-question-answer-systems-bluemix-watson

**Comment by mitchmason** [comment]
that one works for me thanks!

Regards,

Mitchell Mason
Product Manager - Watson Engagement Advisor - Dialog Services

Mobile: 408-981-3165
E-mail: mmason@us.ibm.com


650 Harry Road
San Jose, CA 95120
United States
